### ISSUE TITLE
Setting up ngrok

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#3]
Have a small tutorial on how to use ngrok with leader

**Comment by CamDavidsonPilon** [comment]
1. Download app to the Pi: `wget -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip`
2. Unzip 
3. Make `/opt/ngrok/` folder (need sudo), move `ngrok` file there.
4. Add `ngrok.yml` file
```
authtoken: <add_your_token_here>
tunnels:
  ssh:
    proto: tcp
    addr: 22
    inspect: false
  ui:
    proto: http
    addr: 9000
    subdomain: pioreactor
    inspect: false
  ws:
    proto: http
    addr: 9001
    subdomain: pioreactorws
    inspect: false

```
