### ISSUE TITLE
Experiment markup language

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#397]
Can we package an experiment into a single yaml file that is exportable / importable? Some ideas:

- jobs, automations, and actions can be defined (maybe a similar semantics to Github Actions to define dependencies, i.e od_blank first)
  - settings can be defined in a job section:
  ```yaml
  run:
     stirring:
         target_rpm: 500
     temperature_control:
         automation_name: thermostat
         target_temperature: 30
  ```
- specify _when_ we start jobs after experiment creation
  ```yaml
  run:
     stirring:
         target_rpm: 500
         delay_hours: 1
  ```
- provide a experiment name, desc, metadata generally
- should be mostly independent of config.ini, i.e. we don't care about which PWM channel waste is. 
- existing experiments should be able to be exported into this format
- how do we define changing settings mid experiment?
