### ISSUE TITLE
Disconnecting an automation is possible without the controller stopping / changing state

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#422]
I ran the following profile:

```
experiment_profile_name: new_pid_temperature

metadata:
  author: Cameron Davidson-Pilon

pioreactors:
  leader7:
    jobs:
      stirring:
        actions:
          - type: start
            hours_elapsed: 0.0
            options:
              target_rpm: 400
      dosing_control:
        actions:
          - type: start
            hours_elapsed: 0.05
            options:
              automation_name: chemostat
              duration: 20
          - type: stop
            hours_elapsed: 1.5
      temperature_control:
        actions:
          - type: start
            hours_elapsed: 0.0
            options:
              automation_name: thermostat
              target_temperature: 30
      temperature_automation: # pinging thermostat
        actions:
          - type: update
            hours_elapsed: 3
            options:
              target_temperature: 40
          - type: update
            hours_elapsed: 6
            options:
              target_temperature: 50
          - type: stop
            hours_elapsed: 9
```

Note that I _stop_ the `temperature_automation`, and not the controller. When 9 hours elapsed, the automation disonnected, and the heating PCB stayed _on_. This probably isn't wanted.
