### ISSUE TITLE
How to scale RPM with OD?

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#451]
A request for increasing RPM as (n)OD scales (probably to increase aeration). What's the simplest way to achieve this? What's the _right_ way to achieve this?

**Comment by CamDavidsonPilon** [comment]
Here's an experiment profile that could do it:
```
experiment_profile_name: demo_stirring_repeat

metadata:
  author: Cam Davidson-Pilon
  description: A simple profile that increases RPM with increasing OD

pioreactors:
  testing_unit:
    jobs:
      stirring:
        actions: # after 1 hour, every 1 hour, we increase the RPM in proportion to increase in nOD
          - type: repeat
            hours_elapsed: 1
            interval: 1
            actions:
              - type: update
                hours_elapsed: 0.001
                options:
                  target_rpm: ${{testing_unit:stirring:target_rpm + 10 * (testing_unit:growth_rate_calculating:od_filtered.od_filtered - 1) }}

```
