### ISSUE TITLE
Allow a "break" directive

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#471]
It's awkward to write a profile like: "change temperature the first time X happens". What if actions in the `repeat` block can have an optional `break` directive, which will exit any top-level repeat if the action executes?

```yaml
type: repeat
while: ....
actions:
  - type: update
    if: ...
    break: True # maybe an expression??
    options:
        ...

```

This would require us to keep track of future actions, so we can cancel them...
