### ISSUE TITLE
Improve OD calibration relationships and UI display of data

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactor#559]
A user had a problem that should be solved with the calibration system, but the way calibrations are implemented prevents _both_ calibrated OD readings and raw OD readings from being displayed in the UI (their goal).

Likewise, from a system POV, incoming OD data is indistinguishable between if it's calibrated or not. This means the OD data is undocumented in our DB, and other jobs that use OD data aren't aware either.

This is also apparent in our type system: we only have `ODReadings`, but some applications should accept calibrated OD readings only. 

## Goals
 - [x] Someway to distinguish raw OD vs calibrated OD in our codebase. This could be an MQTT topic (that has significant issues), tags on Structs, a field in the Struct. 
 - [x] Database is aware of calibrated OD readings or not.
 - [x] Overview can display both raw ODs and calibrated ODs.

#### new MQTT topic 
For example, sending calibrated ODs (if any) to `.../od_readings/calibrated_ods` and `.../od_readings/calibrated_od1`, etc. and keeping the existing od topics too. This requires updating all downstream consumers, like: growth-rate, mqtt-to-db, UI-yamls. This does make the UI-yaml easy: just add a new chart yaml targeting this new topic.

But a downstream job is now listening to _two_ topics? How does it decide which to use? Ex: growth rate, which data stream should be used? What if that changes half-way through? 
 - We could make "calibrated" a published setting, and downstream jobs check that via JobManager?

#### _two_ new mqtt topics! 

We keep `.../od_readings/ods` as a heterogenous data stream, and introduce two new streams:  `.../od_readings/raw_ods` and `.../od_readings/calibrated_ods`. Downstream consumers don't need to change, and we can add new sinks for subscribing to specific streams.  It does create a lot of data duplication in MQTT and the database. 

#### new database table or column?
Using the new datasets system, we can get away with a new column for calibrated data (probably a boolean? maybe the calibration name?). Adding a new column to od_readings table makes me nervous, since it's such a big table. 

Actually, we probably want a new table. That way we have data on both raw and calibrated readings, duh. Since it's calibrated data, we don't need to extra metadata like angles, pds, etc. since that's all in the calibration yaml. 

Hiccup if we make a new table: the activity_data table references od_reading only, so this needs to be updated to include calibrated data. 

### What's for sure?

1. A new chart yaml that is for calibrated OD readings. Example:
```yaml
---
chart_key: calibrated_optical_density
data_source: # TODO
title: Calibrated Optical density
mqtt_topic: # TODO
source: app
payload_key: od
y_axis_label: Calibrated Reading
interpolation: stepAfter
fixed_decimals: 3
y_axis_domain: [0.001, 0.05] # good default for near 0 OD, but will break out after growth.
down_sample: true
```
